<?php
echo "
<BR>
<strong>PDB TITLE:</strong> HOW THE ANTI-(METAL CHELATE) ANTIBODY CHA255 IS SPECIFIC FOR THE METAL ION OF ITS ANTIGEN: X-RAY STRUCTURES FOR TWO FAB'(SLASH)HAPTEN COMPLEXES WITH DIFFERENT METALS IN THE CHELATE <BR><BR>
<strong>Chain L:</strong> has MOLECULE name: <strong>IGG1-LAMBDA CHA255 FAB (LIGHT CHAIN)</strong><BR>
<strong>Chain H:</strong> has MOLECULE name: <strong>IGG1-LAMBDA CHA255 FAB (HEAVY CHAIN)</strong><BR>
<strong>HetAtm &nbsp;&nbsp;IN-H800:</strong>has MOLECULE name: <strong>INDIUM (III) ION</strong><BR>
<strong>HetAtm &nbsp;EOT-H801:</strong>has MOLECULE name: <strong>[(1-[(BIS-CARBOXYMETHYL-AMINO)-METHYL]-2-{4-[3-(2-HYDROXY-ETHYL)-THIOUREIDO]-PHENY}-ETHYL)-CARBOXYMETHYL-AMINO]-ACETIC ACID</strong><BR>
";
?>
