<?php
echo "
<BR>
<strong>PDB TITLE:</strong> SOLUTION STRUCTURE OF A PHOSPHOROTHIOATE MODIFIED RNA BINDING SITE FOR PHAGE MS2 COAT PROTEIN <BR><BR>
<strong>Chain A:</strong> has MOLECULE name: <strong>PHOSPHOROTHIOATE SUBSTITUTED PHAGE MS2 RNABINDING SITE</strong><BR>
";
?>
